### ISSUE TITLE
Assets custom path doesn't appear to be working.

### ISSUE THREAD

**Issue by benbarbour** [SvenWerlen/moulinette-core#1]
In my Data folder I have `/assets/props/<many .webp in subfolders>`. If I enter `/assets/props` into the Moulinette Core Settings field called "Assets Custom Path" and then re-index I can see that it updates `/moulinette/images/custom/index.json`, but that file contains an empty array instead of references to the `<many .webp in subfolders>`. Also, I can't find them when I search using the moulinette UI.

**Comment by SvenWerlen** [comment]
This part of the documentation is probably not very clear. Take a look at :
https://github.com/SvenWerlen/moulinette-core/tree/main/docs

In your case, you probably need to add a folder in `/assets/props/` in which you'll put all your assets. Or enter `/assets` in the settings. Let me know if that works

**Comment by benbarbour** [comment]
Hmmm. I tried the symlinking but can't get that to work either. I definitely have the links set up as described.

```
root@foundry:~/foundrydata/Data/moulinette/images/custom# ls -l
total 0
lrwxrwxrwx 1 root root 39 Apr 20 22:15 '2 Minute Tabletop' -> '../../../assets/props/2 Minute Tabletop'
```

The existing folder structure goes `/assets/props/<publisher>/<category X>/<file>.webp`. For example `/assets/props/2 Minute Tabletop/Camp Tokens/Tent, square, 3.webp`. The category folder could be repeated zero-to-many times. Does moulinette scan subfolders?

**Comment by TaylorWatson** [comment]
I'm getting a similar issue as well. Can anyone confirm what is the base path is tries to look? I have this running in a docker, does it start at root or inside the data folder of Foundry?

**Comment by SvenWerlen** [comment]
It looks int the data folder of Foundry. There, you should find a `moulinette/` folder (default path, created by the module). You can use your own path but it must be relative to that data folder. I'll give more flexibility in the future.

**Comment by SvenWerlen** [comment]
After investigation, custom folder works but requires at least one `<name>.mtte` file to let Moulinette know which folder (and its subfolder) to scan. See https://github.com/SvenWerlen/moulinette-core/tree/main/docs
_(documentation has to be improved)_

**Comment by benbarbour** [comment]
Thanks for the quick responses, and a great module! Yeah, the documentation around the custom images could be beefed up a tad. Still, it works quite nicely after I put the .mtte files in place. :)

**Comment by SvenWerlen** [comment]
Thank you for confirming that it works for you now.
