### ISSUE TITLE
Issue with Ernie's Modern UI

### ISSUE THREAD

**Issue by spacegiant** [SvenWerlen/moulinette-core#12]
Hi, I've found an issue where the Moulinette control tools toolbar is not clickable while using Ernie's Modern UI module.
Digging in I've found that Ernie's adds `pointer-events: none` to `.control-tools` but expects the toolbar to have children with class `.control-tool` which it uses to add `pointer-events: all`. The default toolbars follow this pattern of having `.control-tools` with children `.control-tool` but Moulinette doesn't have the child classes on the `<li>` items. Adding the child classes seems to fix the problem but breaks some styling. At a minimum, add `pointer-events: all` to the child elements would make them clickable again.

Is this something that can be fixed in this module?

**Comment by SvenWerlen** [comment]
Thank you for reporting this issue and proposing solutions. I'll investigate this and fix it.

**Comment by SvenWerlen** [comment]
Ok, fixed in `v-2.3.1`. I decided to go with the quick and dirty solution (`pointer-events: all`) for the time-being. I'm not an expert in CSS to fix style with adding `.control-tool`
