### ISSUE TITLE
Moulinette Cloud in Foundry

### ISSUE THREAD

**Issue by Zandman64** [SvenWerlen/moulinette-core#13]
Cannot drag and drop Tiles from Moulinette to Foundry Canvas. It won't actually drag & drop things onto a scene... I'm using the forge, I get the message saying it's been put into the file structure, but nothing comes out.

**Comment by SvenWerlen** [comment]
Please check that you don't have "Drag & Drop" module enabled. This module causes conflicts and produces exactly the behavior that you seem to have.

**Comment by SvenWerlen** [comment]
I'm going to close this due to inactivity, assuming that my previous comment fixed it.

**Comment by Zandman64** [comment]
Hi Sven,

Apologies for not responding sooner. It wasn't the "Drag & Drop" module as
I had that disabled however whatever hard work you've put in the last week
or so in the updates fixed the issue and I and fully use your wonderful
modules now. There are the odd tiles that show up in the browser with a
white background and replicate that when pulled on the canvas but I don't
think that's a Moulitnette issue and it's so few assets that I can live
with that.

Thanks so much for all your hard work, this really is a massively helpful
tool for DM's!

Andi Schipelbaum

**Comment by SvenWerlen** [comment]
Thank you for your answer and your nice comments!
Join our Discord if you want to discuss, propose new features or get some additional support.

**Comment by Zandman64** [comment]
Hi Sven,

I am on your Discord as Zandman. I am an avid DM with very little
coding experience so I will certainly be there for additional support and
to keep up with the amazing stuff you're doing!
