### ISSUE TITLE
thumbnails / images not displayed

### ISSUE THREAD

**Issue by Raileth** [SvenWerlen/moulinette-core#14]
I use the forge for my game hosting requirements, I have uploaded images into the moulinette folders in the forge and indexed them.  (As per the video demo provided by Baileywiki). No thumbnails are shown and I am unable to drag and drop anything onto my canvas

Attached are 2 images, one showing the images in my assets folder on the forge, the other showing a search in foundry using moulinette - as can be seen the assets are there but they are not shown on the search. the default 'free' ones are there and able to be placed but all of the others without thumbnails cannot be placed.

looking at the console the error message is the same for all the images without a thumbnail:- 

moulinette/images/custom/FA%20Assets/Mapmaking/Artificial/Temporary_and_Mobile_Structures/Vehicles/Water/Boat_Mast_Wood_Ashen_A1_5x6.webp:1 Failed to load resource: the server responded with a status of 404 ()

when an image without a thumbnail is placed on the canvas the following error message is displayed:-

foundry.js:36256 Failed to load texture moulinette/images/custom/FA Assets/Mapmaking/Artificial/Decor/Clutter/Kitchenware/_Old_Kitchenware/Campfire_Pan.webp: Invalid URL
loadTexture @ foundry.js:36256
moulinette-tiles.js:426 Uncaught (in promise) TypeError: Cannot read property 'baseTexture' of null
    at Function.createTile (moulinette-tiles.js:426)

its worth noting the asset it is trying to load has a url of : 

https://assets.forge-vtt.com/602fc8a62cfc1cba3ed90ab5/moulinette/images/custom/Forgotten_Adventures/Artificial/Decor/Clutter/Kitchenware/_Old_Kitchenware/Campfire_Pan.webp

![moulinette image 1](https://user-images.githubusercontent.com/7972292/120691095-f1c41080-c49d-11eb-9cbe-3cbe667d3a8d.png)
![moulinette image 2](https://user-images.githubusercontent.com/7972292/120691108-f5f02e00-c49d-11eb-8c13-4370813c0218.png)

**Comment by SvenWerlen** [comment]
I'm planning to do some testing on Forge this week-end.

**Comment by Raileth** [comment]
for info - i have logged on this morning and it is now working fine, As no changes have been made to the module I'm guessing it is a forge quirk with taking time to index the files etc, despite them being uploaded. Happy to provide any other information if it helps

![moulinette image 3](https://user-images.githubusercontent.com/7972292/120773198-04c7f680-c519-11eb-9e73-e0d5176992cc.png)

**Comment by SvenWerlen** [comment]
I'm closing now that issue because I think that the last bugs related to Forge have been fixed. Feel free to re-open it (or submit another) if this is not the case.
