### ISSUE TITLE
Cannot open moulinette due to hasEarlyAccess function when not connected to patreon

### ISSUE THREAD

**Issue by rlach** [SvenWerlen/moulinette-core#15]
System:
Mouilinette 2.6.0
Moulinette tiles 2.6.0(I've disabled others for tests)
Foundry 8.7.0
Pathfinder 2.3.0

When I try to open moulinette browser of tiles/sounds/anything I get following error:
```
TypeError: An error occurred while rendering MoulinetteForge 201: game.moulinette.user.hasEarlyAccess is not a function
    at MoulinetteForge.getData (moulinette-forge.js:103)
    at async MoulinetteForge._render (foundry.js:2042)
    at async MoulinetteForge._render (foundry.js:2729)
```
The window doesn't open. I can see the about window, and I could connect to patreon. After connecting to patreon the issue fixed itself.

**Comment by SvenWerlen** [comment]
Thank you for reporting this!
I fixed it in `2.6.1`
