### ISSUE TITLE
Feature Request: integrate Moulinette content directly into the Foundry File picker

### ISSUE THREAD

**Issue by franckflo** [SvenWerlen/moulinette-core#16]
It would be awesome if we could access the Moulinette content directly when we use the Foundry File picker to select a sound, a token, a template, an image, etc... I would love to have an icon for Moulinette in the file picker that would allow me to search through the Moulinette assets (with preview if possible). That would save a lot of time.

**Comment by SvenWerlen** [comment]
Hi, there is a partial implementation for this. You can configure "Moulinette Picker" to replace the default FVTT picker. It's not yet perfect but it does what you request.
