### ISSUE TITLE
Using Moulinette as file picker

### ISSUE THREAD

**Issue by powerkor** [SvenWerlen/moulinette-core#17]
When enabling the 'replace file picker', the moulinette file picker closes as soon as you click on an image for a tile after you search, doesn't allow to drag-and-drop out of the picker and doesn't show on the canvas after it closes.

**Comment by SvenWerlen** [comment]
Thank you for reporting this. 
I'm not able to reproduce it. Would you mind contacting me on Discord (https://discord.gg/xg3dcMQfP2) on channel #troubleshooting ?

The behavior you describe looks like something I fixed more than 1 week ago. It was related to the list view (expandable folders). Let me know if you can still reproduce it.
