### ISSUE TITLE
Moulinette performs failing HTTP requests, resulting in errors in the console

### ISSUE THREAD

**Issue by ghost91-** [SvenWerlen/moulinette-core#18]
Moulinette seems to perform some requests that do no necessarily succeed (I suppose it has something to do with the cloud integration stuff). This results in errors popping up in the console, which can be disturbing and and distracting when trying to track down other problem that pop us as _actual_ errors in the console. Here is an example of an error produced by Moulinette:

```
GEThttps://boisdechet.org/mtte/user/6ecpswuh6k7lpj4e3n8ahhqiat
[HTTP/2 404 Not Found 115ms]
```
The returned body is just an empty JSON object (`{}`).

I suggest to find some way to avoid this call.

I guess, personally I would also like a setting to completely deactivate any calls to any 3rd party server. That would also be helpful when running foundry in a LAN only setup, without any internet connection.

**Comment by SvenWerlen** [comment]
Thank you for your report. 

First of all, some clarifications:
- boisdechet.org belongs to me. I started very small and couldn't afford expensive hosting provider at the beginning. This is about to change thanks to all the supporters.
- This API call is used for retrieving the user information from the server. 
- I don't call any 3rd party. I don't log anything on my server. I don't use Google Analytics or anything that would track actions from the users. Privacy is really important for me.
- I agree that 404 as response is not ideal. It simply means that you have not linked your account with Patreon. I'll change this behavior to avoid it to be highlighted in the logs.
- I agree that a setting to make it completely offline makes sense (specially if you care about privacy). You won't benefit from external assets but a few people probably only rely on local assets.

**Comment by ghost91-** [comment]
Thanks for the clarifications, I was assuming it was something like that. And also thanks for being so considerate regarding privacy!
I am actually using Moulinette in the way you describe in your last bullet point, so I would be very glad about an option like that :)

Thanks for developing this awesome module btw. :)

**Comment by SvenWerlen** [comment]
Latest core update (3.3.0) implements the configuration. You can now completely disable Moulinette Cloud if you want to. And there is no more requests to boisdechet.org, only to moulinette.cloud (new domain name). I'm closing this issue. Feel free to re-open it if it doesn't fits your needs.

**Comment by ghost91-** [comment]
Thank you so much fo this!
