### ISSUE TITLE
Using S3 as custom directory

### ISSUE THREAD

**Issue by caewok** [SvenWerlen/moulinette-core#2]
Foundry 0.7.9. Moulinette core 0.8.8.

**Issue**
I would like to be able to point to an S3 directory for custom images. I have tried using both an s3:// url and an https:// url in the settings for assets custom path, with no luck. I see the following error in the console (server URL redacted):
> Uncaught (in promise) Directory https://[serverurl].s3.us-west-002.backblazeb2.com does not exist moulinette-forge.js:150:16
>     _onClickButton https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:150
>     AsyncFunctionThrow self-hosted:694
>     (Async: async)
>     _onClickButton self-hosted:1173
>     jQuery 9
>     activateListeners https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:93
>     _render https://[serverurl]/scripts/foundry.js:4537
>     AsyncFunctionNext self-hosted:690
>     (Async: async)
>     _render https://[serverurl]/scripts/foundry.js:5157
>     render https://[serverurl]/scripts/foundry.js:4479
>     _onNavigate https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:120
>     _onNavigate self-hosted:1173
>     jQuery 9
>     activateListeners https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:90
>     _onScroll https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:208
>     _onScroll self-hosted:1173
>     jQuery 8
>     activateListeners https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:105
>     _render https://[serverurl]/scripts/foundry.js:4537
>     AsyncFunctionNext self-hosted:690
>     (Async: async)
>     _render https://[serverurl]/scripts/foundry.js:5157
>     render https://[serverurl]/scripts/foundry.js:4479
>     _onNavigate https://[serverurl]/modules/moulinette-core/modules/moulinette-forge.js:120

**Expected outcome**
I would expect an S3 directory to work similarly to how it works for linking to other Foundry assets. Or maybe this is just a case of needing some documentation for how to properly specify the URL. 

**Use Case**
I am a patreon of FR, and so I have gigs worth of tiles, etc. Putting this sort of stuff in a private S3 box saves me on bandwidth and storage. The space alone would quickly overwhelm the VM storage for the foundry vtt server; S3 is the less costly, more efficient option. 

Thanks!

**Comment by SvenWerlen** [comment]
Could you retry it? In the latest release `1.4.1` of moulinette-core, custom folder should be working according to my tests. Some people reported that very large folder could fail but it worked for other. Let me know if it still doesn't work for you.

**Comment by caewok** [comment]
I think I need a bit more guidance on how to specify the custom folder. I have the S3 set up in Foundry and it works. For example, if I want to set a token image to something in S3, I can use the Image Browser to find it from the Amazon S3 tag. The image will use a URL, for example:

> https://[SERVER_URL].s3.us-west-002.backblazeb2.com/Forgotten_Adventures/Tokens/BLM_Pride_Knights/BLM_Pride_Knight_Gold.webp

If I put a similar URL in the assets custom path setting, however, it doesn't work. 

> https://[SERVER_URL].s3.us-west-002.backblazeb2.com/Forgotten_Adventures/Tokens/

The above setting will throw this error:

> Uncaught (in promise) Directory https://[SERVER_URL].s3.us-west-002.backblazeb2.com/Forgotten_Adventures does not exist

Presumably, it expects the directory to be specified in some different way, but I am not sure what it expects.

**Comment by SvenWerlen** [comment]
Hi, you don't have to specify the SERVER URL. In your case, the custom folder configuration should be:
`Forgotten_Adventures` then put into that folder a `something.mtte` file with the following content:
```json
{
  "publisher": "Forgotten Adventures"
}
```
Documentation is here: https://github.com/SvenWerlen/moulinette-core/tree/main/docs
You can also have some support by joining our Discord: https://discord.gg/xg3dcMQfP2

**Comment by SvenWerlen** [comment]
You'll also find several pinned messages about S3 on our Discord. This could help you.
I'll now close this issue but feel free to re-open it it you still experience issues with it.
