### ISSUE TITLE
Annoying Shortcut

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-core#22]
Hi.

Everytime I press Control + F for Quick Search it opens this and I can't find how to disable.

![image](https://user-images.githubusercontent.com/4999783/135679695-e60dcfcc-fe4b-4711-a007-9ec9851dbafc.png)

**Comment by SvenWerlen** [comment]
You can change or disable the shortcut in the configuration Keybind lib
![image](https://user-images.githubusercontent.com/938060/135684466-e619ab03-af12-4755-9a1e-07b1ea0842a1.png)
