### ISSUE TITLE
Make the Buttons Match the Controls

### ISSUE THREAD

**Issue by Baxmann** [SvenWerlen/moulinette-core#24]
The buttons and styling of the Moulinette Buttons are not the same. The buttons go horizontally across instead of vertical, like all the other controls.

**Comment by SvenWerlen** [comment]
Has been implemented in moulinette-core `4.2.0` (will be released beg. February 2022)

**Comment by SvenWerlen** [comment]
See screenshot :
![Screenshot_20220125_000210](https://user-images.githubusercontent.com/938060/150914149-b65a2092-43cb-4b9f-bfe6-91a4e622386e.png)
