### ISSUE TITLE
Trigger a re-index/index load in a macro

### ISSUE THREAD

**Issue by crimsonknave** [SvenWerlen/moulinette-core#25]
:wave: I've built a macro that generates an NPC for me and posts it to chat. Part of that is picking a random image for them and I'm using `game.moulinette.cache.cache["moulinette/images/custom/index.json"]` as the source of my images. However, it appears that cache isn't populated until I open one of the UI dialogs that would search it. So, every time I log into the UI I need to open one of those before my macro will work.

Is there already a function I can call to build that cache? If not, can the function that generates it be exposed on `game.moulinette` somewhere?

cc https://github.com/crimsonknave/foundryvtt-macros/pull/1 (where I use the cache)

**Comment by SvenWerlen** [comment]
Hi!
There is no such function but I'll add one in the future to let other modules/macros use it. 
In the mean time, you can use the following snippet
```
const user = await game.moulinette.applications.Moulinette.getUser()
const index = await game.moulinette.applications.MoulinetteFileUtil.buildAssetIndex([
      game.moulinette.applications.MoulinetteClient.SERVER_URL + "/assets/" + game.moulinette.user.id])
```
