### ISSUE TITLE
In V9, the Toolbar icon renders outside the vertical order, nonfunctional

### ISSUE THREAD

**Issue by apoapostolov** [SvenWerlen/moulinette-core#26]
The other icon next to it is Narrator Tools (I will inform its dev separately)

![image](https://user-images.githubusercontent.com/4083812/146644602-9cf9c65f-7a02-4ea7-9a2d-0f16ca8641a6.png)

**Comment by SvenWerlen** [comment]
Hi there,
I just released a new version (`4.0.0`) that supports V9. It is not yet perfect but it makes it functional.
Direct JSON URL : `https://raw.githubusercontent.com/SvenWerlen/moulinette-core/Feature/0.9.x/module.json`
