### ISSUE TITLE
Assets custom path is not used

### ISSUE THREAD

**Issue by Tupsi** [SvenWerlen/moulinette-core#29]
I tried the option, but the path I entered does not get indexed when I hit the index button. I can see in the console that only stuff from moulinette/images/custom gets scanned, but my /assets I entered is getting ignored.

![image](https://user-images.githubusercontent.com/3730499/147470337-37962725-484d-4bd5-9560-c9a3af4e8df0.png)

The game itself can access /assets just fine and if I bother to create a symlink in custom which points to /assets everything in there gets scanned. Just using your custom setting does not yield any results.

**Comment by SvenWerlen** [comment]
Sorry for my late answer. Custom path should never start with "/". Try to put `assets` only. And you should also make sure to have at least one file with extension `.mtte` as explained in the following documentation : https://github.com/SvenWerlen/moulinette-core/tree/main/docs

**Comment by Tupsi** [comment]
For later reference and other people coming here. If you want to index everything, like say on a S3 storage, just put a "." in there.
