### ISSUE TITLE
Custom Asset Directory

### ISSUE THREAD

**Issue by insquared** [SvenWerlen/moulinette-core#3]
Most of my games are run on Forge-vtt, and we do not have access to the module data folder or data folder in general, it would be great if we can tell the module to look for assets in a different location.

**Comment by SvenWerlen** [comment]
Hi, can you provide me an example of path that you typically use? 
The implementation of moulinette is based on the FilePicker. So if you can browse for a file, I can definitively make it work in Moulinette.

**Comment by insquared** [comment]
I've contacted forge for help, I simply misused. My bad!
