### ISSUE TITLE
Moulinette FilePicker generates "stack size exceeded" errors

### ISSUE THREAD

**Issue by SvenWerlen** [SvenWerlen/moulinette-core#31]
I have (sometimges) trouble accessing the default filepicker when I enabled to use the moulinette one and get this in the console:

![image](https://user-images.githubusercontent.com/938060/148951027-8d51200d-6471-4e6b-9f9c-b305ee530ba2.png)

only only happens to filepickings where I sucessfully selected an object in my s3 storage earlier. If I use a filepicker on an item where the image for instance still resides on the server the default filepicker still works
it still works with some files/places on s3. could it be that the place the default fp is pointed at has to many objects for mounlinette to handle in what ever stack your are using there @Dorgendubal | Moulinette
the bad directory has indeed a few items, its the place I stuffed the wow icons away from wowhead, which are roughly 22k
oh just disabled everything and the error still persists, so I guess its a core problem. I will go over to that discord then and bug someone there 🙂

**Comment by sneat** [comment]
For me, it seems to happen over time when rendering large numbers of scenes with base64 thumbnails.

**Comment by SvenWerlen** [comment]
I'll close this issue because it is not happening frequently (I cannot reproduce it) and it doesn't affect many people.
