### ISSUE TITLE
Index Sounds not working

### ISSUE THREAD

**Issue by sheathompson** [SvenWerlen/moulinette-core#34]
For some reason, the audio files I put into the custom folder you mentioned in your guide, don't show up in the sound list after indexing. The list is empty, please help

**Comment by SvenWerlen** [comment]
Hi, in the latest release, there is a Moulinette Help that provides more information about your custom configuration.
Could you please make a screenshot of it? See example
![image](https://user-images.githubusercontent.com/938060/151728362-34770dd0-d381-44c8-8f08-d4dbf94aee4b.png)

**Comment by Mist-Hunter** [comment]
![image](https://user-images.githubusercontent.com/6420684/152688901-b320dc72-d23c-4092-97c9-7ac8bed18f43.png)

![image](https://user-images.githubusercontent.com/6420684/152689084-6c35d7cd-60e2-4c6e-a3ac-2d56bdcc6599.png)

I don't know if my issue is related to @sheathompson, but my indexing does complete after sometime, but not all the sub directories are showing up as packs in the "Sounds" tab. In the first SS, you can see that it shows 39 sub-folders in 'Sound Effects', but in the second screenshot I'm only seeing 6 sub-directories available under 'Sound Effects' in the actual drop down.

Thanks for you awesome software!

**Comment by Mist-Hunter** [comment]
I'm wondering if there's a character filename limit? I'm thinking some of my paths are maybe too long?

**Comment by Mist-Hunter** [comment]
For me, I'm 90% sure the issue is NOT path length but file extensions.

The sounds that are not showing up are:
```
.FLAC 
.webm
```
Maybe be others, but those are clear to me.

**Comment by SvenWerlen** [comment]
WebM is supported but will be detected as video file (tiles).
Flac is not supported. Currently, only .mp3 and .ogg are indexed.

**Comment by Mist-Hunter** [comment]
Thanks for the quick reply! Good to know this expected behavior.

Any chance FLAC or Webm might be support in the future? They are both listed under Foundry's main media optimization guide here https://foundryvtt.com/article/media/

**Comment by SvenWerlen** [comment]
Yes, I will. WebM is more problematic because I'll not be able to distinguish between a sound and an animated map. I need further investigation. I will probably need about 1-2 weeks to figure out the best way to support it.

**Comment by Mist-Hunter** [comment]
Thanks for all your work. Foundry is so much better with your modules.

**Comment by SvenWerlen** [comment]
Thanks a lot!

Finally, it was not so complicated to add. 
A new release of moulinette-core and moulinette-sounds (`v-3.4.0`) has been created. According to my tests, it should work

**Comment by Mist-Hunter** [comment]
Verified. All my folders are now visible. Champion!

**Comment by SvenWerlen** [comment]
Great!
