### ISSUE TITLE
Moulinette File Picker doesn work with Tile Browser

### ISSUE THREAD

**Issue by robnmeyer** [SvenWerlen/moulinette-core#35]
The normal tile browser allows you to browse for a tile to place.  When using Moulinette to replace the file picker, you can't drag and drop tiles onto the canvas like you could when using the default.

Generally, as an aside, it would be nice to configure Moulinette to be used as the default file browser, tile picker etc.   And along with that, it would be good to be able to configure Moulinette to not show the Hammer, Heart, Magnifier, etc.  I am trying to cut down on menu items and if there already menu items that do the file and tile picking, browsing, etc, it would be good to just use those instead of having dupes.

**Comment by SvenWerlen** [comment]
Regarding the second part of your request, the new version of moulinette lets you remove the controls (hammer, heart, magnifier) from the menus other than the moulinette layer. 

![image](https://user-images.githubusercontent.com/938060/162581596-03886257-6c69-4dbf-8fd7-f07b64b90fc5.png)
