### ISSUE TITLE
Cannot figure how to add more images

### ISSUE THREAD

**Issue by Nedrapter** [SvenWerlen/moulinette-core#36]
Hello!
After following Baileywiki's video guide on how to make Moulinette work on The Forge, i've successfully added Forgotten Assets to the indexed folders. However I'm trying to add a new folder with tokens and they don't show up in the search.
![image](https://user-images.githubusercontent.com/74311190/155415588-2ae02e07-84cc-411e-a1c4-de8504897fb5.png)
This is what the indexing path says.
The index.json is in the same folder as those two folders and I've tried re-indexing images. What am I missing?

**Comment by SvenWerlen** [comment]
That looks good (15 subfolders found). Did you wait until the indexing process is complete? You can notice this by typing something into the search bar. When the index process is complete, the content of the page refreshes itself and the text disappears.

Also, could you check the logs if you see any error?
Finally, you can enable "debugging" in the configuration of Moulinette and could see more logs which could help.

**Comment by Paure42** [comment]
For me it was because of this `Uncaught (in promise) Directory modules/baileywiki-maps-premium-towns does not exist or is not accessible in this storage location`
I just created the directory manually

**Comment by SvenWerlen** [comment]
Will be fixed (without needing to create the directory manually) in moulinette-core `4.5.0` (will be released soon). Thanks for reporting this!
