### ISSUE TITLE
[Suggestion] Add option to remove Moulinette control tools from all submenus

### ISSUE THREAD

**Issue by marcstraube** [SvenWerlen/moulinette-core#37]
If you use many modules, it's most likely that you already have more than enough control tools in the left menu. It would be nice to have an option that removes the Moulinette control tools from all submenus except Moulinette's own to declutter the interface a little bit.

**Comment by TheBiggerBadderWolf** [comment]
I came here to post the same request, would appreciate this being added as a togglable option.

**Comment by SvenWerlen** [comment]
The latest release of Moulinette Core provides such a configuration:
![image](https://user-images.githubusercontent.com/938060/161434042-7fc4490b-43ec-4d72-b3be-331741bbfd94.png)

Let me know if this is not implemented the way you'd like to be.
