### ISSUE TITLE
FileExists check fails when game hosted on The Forge 

### ISSUE THREAD

**Issue by rikmarais** [SvenWerlen/moulinette-core#39]
The [`moulinette-file-util.js` `fileExists` method](https://github.com/SvenWerlen/moulinette-core/blob/a422f51e276bc9afb03816ec52f5f24ceb70719b/modules/moulinette-file-util.js#L105) currently always fails in a game hosted on The Forge. This results in an attempt to reupload the file, which shouldn't be necessary.

This is because the `FilePicker` returns an absolute path for the file `upload`ed or `browse`d which includes The Forge's user specific assets library baseURL.

This should be able to be fixed by prepending The Forge's user specific assets library path to the relative path before comparison when running on The Forge, for example:

```js
if (typeof ForgeVTT !== "undefined" && ForgeVTT.usingTheForge) {
      // ForgeVTT FilePicker returns files with path inclusive of basePath, which is the current user's asset library
      const theForgeAssetsLibraryUserPath = ForgeVTT.ASSETS_LIBRARY_URL_PREFIX + (await ForgeAPI.getUserId() || "user");
      path = (theForgeAssetsLibraryUserPath ? theForgeAssetsLibraryUserPath + "/" : "") + path;
      return parentFolder.files.includes(path) || decodedPaths.includes(path);
}
```

**Comment by SvenWerlen** [comment]
Thank you for reporting this and sorry for the delay.
It's fixed in `v-4.10.3` and `v-10.0.5`. 
_(In V9, you need to uninstall module and re-install to force getting the latest)_
