### ISSUE TITLE
Non-host GMs can't use Moulinette for games hosted on The Forge

### ISSUE THREAD

**Issue by rikmarais** [SvenWerlen/moulinette-core#40]
Unless an S3 bucket is configured which specifies a base URL, Moulinette references assets by relative path. 
When hosted on The Forge, using the relative path will try to access the game host's asset library rather than the current user's. This means that non-host GMs can't reference their own Moulinette assets.

If running on The Forge and not using an S3 bucket, the path to the current user's assets library should be the base URL. Code like the following in [`moulinette-file-util.js` `getBaseURL`](https://github.com/SvenWerlen/moulinette-core/blob/a422f51e276bc9afb03816ec52f5f24ceb70719b/modules/moulinette-file-util.js#L40) could be used to get the base URL of the current user's assets library.

```js
if (typeof ForgeVTT !== "undefined" && ForgeVTT.usingTheForge)  {
      const theForgeAssetsLibraryUserPath = ForgeVTT.ASSETS_LIBRARY_URL_PREFIX + (await ForgeAPI.getUserId() || "user");
      return theForgeAssetsLibraryUserPath ? theForgeAssetsLibraryUserPath + "/" : "";
}
```

**Comment by SvenWerlen** [comment]
Thank you for reporting this. I'll have to check this by myself to better understand how paths are defined on The Forge.

**Comment by SvenWerlen** [comment]
Implemented in `v-4.5.1` (moulinette-core). It did fix the issue for non-host GMs. 
However, I'm not 100% sure of the impact for host GM (who will also have their baseURL changed). 
I'll monitor any issue related to this.

**Comment by SvenWerlen** [comment]
Had to roll it back do to use of "await" in non-sync function. Requires more effort.

**Comment by SvenWerlen** [comment]
I have been able to do all the required changes to make that function asynchronous. The new modules are available for beta testing. See : https://www.patreon.com/posts/66471992

**Comment by rikmarais** [comment]
Great! Thank you for your hard work
