### ISSUE TITLE
Getting net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK) when searching

### ISSUE THREAD

**Issue by robnmeyer** [SvenWerlen/moulinette-core#41]
After indexing when searching for a tile (any), I am getting a net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK).  I don't think I've touched my configuration in a very long time, but I am running the latest code.  Perhaps I need to do something different.

![Screen Shot 2022-05-09 at 5 13 15 PM](https://user-images.githubusercontent.com/16228525/167499478-56407a7d-5919-414b-a439-7be7d3557e2d.png)

**Comment by robnmeyer** [comment]
Hmm.  The problem went away.  Even with local only configurations, does Moulinette still require connectivity to your cloud system to work?

**Comment by SvenWerlen** [comment]
There is a configuration that lets you disable Moulinette Cloud entirely. This should remove the requirement to connect to my server. Btw, I don't track or do anything of that kind on my server. That URL is for retrieving the list of assets that are available
