### ISSUE TITLE
Unable to load local Tiles

### ISSUE THREAD

**Issue by DarkPhonix5097** [SvenWerlen/moulinette-core#42]
Hey when I try to load my local files vie Moulinette an error apears 

![image](https://user-images.githubusercontent.com/48560216/170241895-5af88c0e-1fa6-45e6-a931-c2d9a531c50b.png)

So I cannot find any of my images via moulinette and nothing happens when I click on a pack .
In the Console is another error if i try to click on a pack in the Tile section 
![image](https://user-images.githubusercontent.com/48560216/170242145-4ceaf8e2-5e39-471e-bebf-a73225e154fa.png)

**Comment by SvenWerlen** [comment]
Could you please try again? There was a server issue a few days ago and this could be related. It was fixed.

**Comment by SvenWerlen** [comment]
I assume that this error doesn't happen any more.
