### ISSUE TITLE
Old Feature request

### ISSUE THREAD

**Issue by Nedrapter** [SvenWerlen/moulinette-core#43]
I see that while using the File Picker , scrolling down does not load more assets as it used to be. I don't find this change useful at all, since the amount of assets display at start are rarely enough. Can we have at least a toggle to use the previous load-scroll functionality? Which moulinette version was the last to have that? I need to switch there.

**Comment by SvenWerlen** [comment]
Sorry for my very very late reply on this. 
Is this still the case (auto-scroll)? I tested it and it seems to work fine on my side.
I close this issue but feel free to re-open it if it's still not fixed for you.
