### ISSUE TITLE
Use the higher access one when 2+ subs to the same Patreon are detected by Moulinette

### ISSUE THREAD

**Issue by admiralnlson** [SvenWerlen/moulinette-core#44]
Hello,

I am subbed to the Moulinette patreon at the "Dwarf miner" tier.
And I subbed to the "Mad Cartographer" creator Patreon at the "Essentials Bundle" tier which does not grant integration with Moulinette. Finally I upgraded to the "All The Things™" tier which does.

Moulinette detects this as 2 different subs, until I would imagine end of the month after which only the higher-level sub will remain:
![image](https://user-images.githubusercontent.com/4472669/175563984-f69f1c82-de42-4626-86c9-96c4363a1b0b.png)

The issue is that the assets/scenes/.. are not showing up in Moulinette Cloud I suspect b/c of the second, lower-level one.
Moulinette should in this case unlock the content and ignore the lower-level of sub which does not support integration.

I realize this is maybe not an actual moulinette-core issue and rather something to be changed in the internal logic of your webserver but I thought logging it here might be good enough.

Thanks.

**Comment by SvenWerlen** [comment]
Thank you for reporting this.
This is a special use case, indeed. I implemented a fix for this and deployed it on my server.
It is obviously difficult to me to test it with a real account but I successfully implemented a test case for it.
Could you please try again and confirm if this works or not?

**Comment by admiralnlson** [comment]
@SvenWerlen Oh wow, that was fast! And I can confirm your fix is working perfectly also.

Thanks very much!

**Comment by SvenWerlen** [comment]
Great! Thank you for confirming it.
