### ISSUE TITLE
4.8.0 beta - ForgeVTT.usingTheForge check skipped

### ISSUE THREAD

**Issue by rikmarais** [SvenWerlen/moulinette-core#45]
Hey there 👋 
Thought I should give a heads-up while this version is still in beta

This issue is specific to https://github.com/SvenWerlen/moulinette-core/commit/f0d9156de91546e7f414c50ec1661717cac9ca03

There is a check that's currently being skipped, resulting in the Moulinette Filepicker being used on The Forge, resulting in failed uploads.

```js
      /*
      if (typeof ForgeVTT != "undefined" && ForgeVTT.usingTheForge) {
        console.log("MoulinetteFileUtil | Uploading with The Forge")
        return await ForgeVTT_FilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions());
      } else {
        return await FilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions());
        const timeout = game.settings.get("moulinette-core", "filepickerTimeout")
        return await game.moulinette.applications.MoulinetteFilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions(), { notify: false, timeoutMs: timeout * 1000, onTimeout: function(msg) { console.error(`Moulinette FileUtil | Upload failed due to timeout with your server. Try increasing the timeout in Moulinette configuration. Currently ${timeout} seconds.`);} });
      }
      */
      const timeout = game.settings.get("moulinette-core", "filepickerTimeout")
      return await game.moulinette.applications.MoulinetteFilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions(), { notify: false, timeoutMs: timeout * 1000, onTimeout: function(msg) { console.error(`Moulinette FileUtil | Upload failed due to timeout with your server. Try increasing the timeout in Moulinette configuration. Currently ${timeout} seconds.`);} }); 
```

**Comment by SvenWerlen** [comment]
Thank you for reporting this. 
I replaced the FilePicker from The Forge to be able to make the upload timeout configurable for people.
According to my tests, it still worked. Do you know if the failed upload is due to a timeout?

**Comment by rikmarais** [comment]
> Do you know if the failed upload is due to a timeout?
Unfortunately not a timeout, I'm afraid. 

This was the error I saw and can reliably replicate when uploading new assets: 
![image](https://user-images.githubusercontent.com/34374883/178993624-869ab657-37d8-4289-afc0-29aba11937a2.png)
![image](https://user-images.githubusercontent.com/34374883/178993632-57711779-93d5-430a-811d-2e8eed36bc5a.png)

I think that the issue arises when hosting on the Forge because the `FilePicker` and its `upload` functions are different.
If running on The Forge, using the `MoulinetteFilePicker` rather than the `ForgeVTT_FilePicker` will likely cause problems.

```js 
await ForgeVTT_FilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions());
```
Versus
```js
await game.moulinette.applications.MoulinetteFilePicker.upload(source, folderPath, file, MoulinetteFileUtil.getOptions(), { notify: false, timeoutMs: timeout * 1000, onTimeout: function(msg) { console.error(`Moulinette FileUtil | Upload failed due to timeout with your server. Try increasing the timeout in Moulinette configuration. Currently ${timeout} seconds.`);} });
```

Using `ForgeVTT_FilePicker` is a requirement when running Foundry on The Forge. 
Its `upload` method is responsible for making sure that the asset being uploaded goes into the Forge Assets Library rather than the Forge user's data directory. 

It's possible that this wasn't noticed during testing because if the assets in the Moulinette Scene or Tile (or other) being imported were already present in the test Forge user's Assets Library, another `upload` wouldn't have been attempted and the error would have not been seen.

**Comment by SvenWerlen** [comment]
4.8.0 beta won't be released. The timeout implementation doesn't seem to be required anymore.
