### ISSUE TITLE
Using alternate directory for moulinette store with symlinks doesn't work on windows

### ISSUE THREAD

**Issue by theksi** [SvenWerlen/moulinette-core#46]
Hello,

Running on foundry 9.269, with moulinette core 4.7.0

I've been extensively using moulinette on a MAC system where all my assets are stored under the /sharedassets/ directory, beneath this directory sits de moulinette directory. This setup was done using symbolic links

I had to setup the same environment on a windows machine, and I used a windows logical link . When I try to generate my assets index,  I am getting the following error

````
moulinette/tiles/custom does not exist or is not accessible in this storage location
```

If I remove the link and launch an indexation, moulinette creates an "empty" directory tree and indexes the game icons.

I am almost certain that it worked before.

Is there any way to solve this ?

**Comment by theksi** [comment]
Hello
I kind of solved by removing the link and replacing it with a junction using `mklink /d /j destination source`

**Comment by theksi** [comment]
solved by creating a junction instead of a shortcut

**Comment by SvenWerlen** [comment]
Hi!
For your information, the recent versions of Moulinette provides a UI to let you pick and choose a folder and it to the source to be indexed. It is much easier than the old way of doing it (that you use).
