### ISSUE TITLE
V10 not working in foundry vtt with WHFRP4e

### ISSUE THREAD

**Issue by StevenEvans1966** [SvenWerlen/moulinette-core#48]
When I enable moulinette-core in my WHFRP4e world navigable scenes do not appear.  There is no error reported in the console.

**Comment by MoonBrew** [comment]
Same with D&D 5e.

**Comment by SvenWerlen** [comment]
According to the community, this seems to be due to the update of moulinette modules.
Can you try uninstalling the modules and re-installing them? This seems to fix it. 
Make sure that all versions of Moulinette modules are `10.0.1` or more.

**Comment by StevenEvans1966** [comment]
OK that worked thanks On 11 Sept 2022 17:34, Sven Werlen ***@***.***> wrote:
According to the community, this seems to be due to the update of moulinette modules.
Can you try uninstalling the modules and re-installing them? This seems to fix it.
Make sure that all versions of Moulinette modules are 10.0.1 or more.

**Comment by TheMathKing** [comment]
I can confirm, Moulinette would not update automatically in Foundry, I had to reinstall it to V10 to get it to work. Scenes loaded afterwards.

**Comment by SvenWerlen** [comment]
I'll announce this issue on Patreon to inform everyone.
