### ISSUE TITLE
[Bug] File Pickier - Searching - Pressing [ENTER] brings up default picker instead of searching.

### ISSUE THREAD

**Issue by Kosyne** [SvenWerlen/moulinette-core#49]
Foundry: 9.269
Firefox
Moulinette Core: 4.10.1
Pathfinder 2E

1. Open sheet
2. Click avatar to bring up file picker
3. type search query in
4. hit [enter]
5. Instead of searching, the Moulinette file picker closes and the default file picker opens

**Comment by SvenWerlen** [comment]
Fixed in moulinette core `v-4.10.2` (V9) and `v-10.0.3` (V10).
Thank you for reporting this! I also appreciate the steps for reproducing it :-)
