### ISSUE TITLE
Moulinette Image Search: missing documentation about Bing API

### ISSUE THREAD

**Issue by franckflo** [SvenWerlen/moulinette-core#5]
Hi, it looks like Image Search now requires an API key. I've looked online for ways to acquire such a key but haven't found anything free. Could you provide proper documentation about that process?

**Comment by SvenWerlen** [comment]
Hi, the process of getting your API key is described on the submodule docs: https://github.com/SvenWerlen/moulinette-imagesearch 
Let me know if some steps are not clear.

**Comment by franckflo** [comment]
Hi, Apologies, I had missed that documentation yesterday. I had actually managed to get the API key after posting the question, stumbling through the process. I reviewed the documentation, it fits what I went through. I may just add to recommend to go for the free pricing tier, as it seems enough to just do image queries.

**Comment by SvenWerlen** [comment]
Thanks for your feedback, I'll improve the documentation to include going for the free pricing tier.
