### ISSUE TITLE
TypeError: Cannot set property active of #<InteractionLayer> which has only a getter

### ISSUE THREAD

**Issue by PsykotikDragon** [SvenWerlen/moulinette-core#50]
It keeps throwing an error in Moulinette-Core
running A5E system (0.8.5) on Foundry (v10.284)
![image](https://user-images.githubusercontent.com/52022617/188787422-8fa15618-cb4a-4338-affd-1399f5ed4018.png)

**Comment by SvenWerlen** [comment]
Hi there,
V10 issues can be resolved by uninstalling moulinette modules and re-installing them again. I don't know exactly why the update doesn't work but other users report that it fixes it. I'll close this issue but feel free to re-open it if it doesn't solve it.
