### ISSUE TITLE
V10 duplicate folders on scene import

### ISSUE THREAD

**Issue by Norskov** [SvenWerlen/moulinette-core#51]
I was trying to import Ostenwold scenes from Tom Cartos, but instead of collecting it all in a single folder, it created a folder called Tom Cartos for each scene, as shown in the attached screenshot.

![image](https://user-images.githubusercontent.com/6616991/189723335-2cd35647-5cf1-4e9c-9544-970fa908aa17.png)

**Comment by Norskov** [comment]
This might be the wrong repository for the issue, as it appears to be in the moulinette-scenes repo.

I've created a PR there: https://github.com/SvenWerlen/moulinette-scenes/pull/6

**Comment by SvenWerlen** [comment]
Thanks a lot for reporting it and fixing it!
I tested and merged everything
_Note : yes, it's OK to create issues on the main "moulinette-core" project._
