### ISSUE TITLE
Compatibility Warns

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-core#54]
Hi!

Is it possible to remove these warns?
![image](https://user-images.githubusercontent.com/4999783/193456802-a0d5b006-5d54-4763-96d5-0deb8b9ee9c3.png)

tks

v10 last stable

**Comment by SvenWerlen** [comment]
Hi!
I have no clue on how to get rid of these warnings. The modules are compatible with V10.

**Comment by brunocalado** [comment]
> Hi! I have no clue on how to get rid of these warnings. The modules are compatible with V10.

I prevent these warnings with this:

![image](https://user-images.githubusercontent.com/4999783/198910270-01ea61f2-8c75-42d5-abb4-03974c8dc5fe.png)

```json
  "compatibility": {
    "minimum": "10",
    "verified": "10"
  },
```

**Comment by SvenWerlen** [comment]
Oh, that was very useful!
I added `"verified": "10"` on my module.json files to fix it! 
Thanks a lot
