### ISSUE TITLE
Drag-and-drop tiles seem to work EXCEPT for the dragging and dropping

### ISSUE THREAD

**Issue by miromonti** [SvenWerlen/moulinette-core#55]
As the title of this issue indicates, dragging a tile from Moulinette ends with an error and no tile.

The action of drag-and-drop seems to work: "Downloading image(s) images in the background" is displayed and Moulinette performs file tasks in the background, but no tile result from that drag-and-drop convenience. Here's a capture from the console:

![Screen Shot 2022-10-15 at 7 13 59 PM](https://user-images.githubusercontent.com/38819125/196014954-d145dfc8-8779-4fbd-a28e-f98db06b96e0.png)

While that doesn't work, I manually place a tile and navigate to the location of the image file.

To be sure, I tested using Find the Culprit with just Moulinette Core and Moulinette Tiles and the result is the same.

FoundryVTT 10.288
Call of Cthulhu 7th Edition (Unofficial) 0.9.1
Moulinette Core 10.0.5
Moulinette Tiles 4.9.1
Find the Culprit 1.4.6

**Comment by SvenWerlen** [comment]
Thank you for this detailed report.
You don't have the latest version of Moulinette Tiles. It should be at least `10.0.1` or it won't be compatible with V10. 
Latest version is `10.2.0`. You'll probably have to uninstall your current Tiles module and re-install it.
Sorry for my late answer.

**Comment by miromonti** [comment]
Thanks for this update. Seems that uninstall-and-reinstall is the the way to "reinvigorate" many modules for Foundry 10.

As of this writing, Moulinette Core is version 10.1.2. I don't see 10.2.0 in-app or on the Foundry site. You know better, of course; I'm simply reporting. Anyway, 10.1.2 does the trick and all's well.

Thanks so much for your work.

**Comment by SvenWerlen** [comment]
Thanks for confirming this.
Latest Core version is `v-10.1.2` indeed.
Latest Tiles version is `v-10.2.1`. 
You can always check which version is latest on the GitHub main page :
![image](https://user-images.githubusercontent.com/938060/199367996-79bd7ac3-0c28-4080-9867-1f2982d98e53.png)
