### ISSUE TITLE
"s3ForcePathStyle": true is ignored

### ISSUE THREAD

**Issue by Q-efx** [SvenWerlen/moulinette-core#57]
Some alternative implementations use "s3ForcePathStyle": true, which basically moves domain bucket names to path style bucket name.

ie: 

foundry.s3bucket.com

becomes: s3bucket.com/foundry

Foundry VTT itself recognizes this setting. This module doesn't recognize it. It still tries to open: foundry.s3bucket.com instead of s3bucket.com/foundry

Error: 

moulinette-file-util.js:523 Moulinette FileUtil | Couldn't load source https://foundry.s3bucket.com/moulinette/images/custom/index.json. Response :  undefined

**Comment by SvenWerlen** [comment]
Based on your last comment (issue in Foundry core), I close this issue.
