### ISSUE TITLE
[Feature Request] Moulinette Sounds Opus Support

### ISSUE THREAD

**Issue by Grandsome** [SvenWerlen/moulinette-core#64]
From the documentation, I've seen that moulinette sound indexing only supports .wav, .mp3 and .ogg files, yet Foundry also support and [recommands](https://foundryvtt.com/article/media/) .opus files for sound media storage and given that [opus](https://caniuse.com/?search=opus) is supported by more browsers than [ogg](https://caniuse.com/?search=ogg) it would be sensible for moulinette sound to support opus also.
Thanks.

**Comment by vohk** [comment]
Oh, a big second to this one. I'd just finished converting my Foundry audio to opus to save on space and was trying to figure out why Moulinette was no longer indexing them.

**Comment by SvenWerlen** [comment]
This is now implemented in moulinette-core `v-11.2.0` and also requires moulinette-sounds `v-11.1.0`.
