### ISSUE TITLE
Moulinette favorites: animated assets do not display image when on the favoritte window

### ISSUE THREAD

**Issue by franckflo** [SvenWerlen/moulinette-core#69]
When I set an animated asset (typically a Webm file from the Jb2a package), there is no image to represent it in the moulinette favorite window. See screenshot. Would it be possible for Moulinette to let us pick one of the frames of the animation as the thumbnail maybe ? or have it pick frame automatically ?

![image](https://github.com/SvenWerlen/moulinette-core/assets/80221412/44bff481-d6cc-4312-b3aa-f8f67af1b6f5)

**Comment by SvenWerlen** [comment]
It took me some time to start working on this. 
I fixed it in `v-11.1.2`. I also noticed a few more bugs (mainly history tab) that I fixed.

**Comment by franckflo** [comment]
Hi there, thanks for looking into it. What is it supposed to look like now? I have Moulinette Core at 11.7.3 and Moulinette Tiles at 11.1.2 and the Favorites for animated items still have placeholder thumbnails. Is it only fixed for new favorites, or do I need to change a setting to activate the fix ? It pretty much looks the same after the update.

![image](https://github.com/SvenWerlen/moulinette-core/assets/80221412/89fef712-574e-43c7-a7a5-dcf8371bb602)
