### ISSUE TITLE
Moulinette

### ISSUE THREAD

**Issue by docmeger4** [SvenWerlen/moulinette-core#70]
I just updated to the newest version of Foundry VTT this am (Version 11 build 313). My Moulinette tools are not there any more. I tried uninstall and reinstall on all Moulinette packages to no avail. This was working on my prior v11 build a couple of days ago. Is this just an issue related to the update and Moulinette will be updated shortly to work with the latest version?

**Comment by SvenWerlen** [comment]
I also upgraded to build 313 and the module still works as expected. Could you check the console logs (F12) to see if there is any issue blocking Moulinette modules to load?

**Comment by docmeger4** [comment]
Ok. I am in the Moulinette discord server at the moment. My screen name is Dorothear.

Sent from my iPhone

On Oct 9, 2023, at 2:09 PM, Sven Werlen ***@***.***> wrote:

﻿

Attachments have not been kept (by GitHub). I can't see them.
I'm also available on Discord (#dorgendubal). It might me easier for me to help you on this.

**Comment by SvenWerlen** [comment]
The issue was caused by the fact that FoundryVTT sometimes deactivates modules during a migration.
After re-enabling them under "Modules management", everything was back and running again.
