### ISSUE TITLE
Nested folder paths replaced with %2f when indexing

### ISSUE THREAD

**Issue by woodwardj** [SvenWerlen/moulinette-core#73]
Images in subfolders have their paths changed from / to %2f whenever there are images in the folder.   It does use a / when the folder is empty as in example below.

Example: base folder is images/tokens with auto 1st/2nd level

images/tokens/FA_Assets/Mapmaking/Artificial/Decor%2FClutter%2FKitchenware%2FCauldrons%2FCauldron_Metal_Gray_A_1x1.png

should be: images/tokens/FA_Assets/Mapmaking/Artificial/Decor/Clutter/Kitchenware/Cauldrons/Cauldron_Metal_Gray_A_1x1.png

![moulinette_nested_folder_path_issue](https://github.com/SvenWerlen/moulinette-core/assets/7428331/95b457f8-1a00-4145-937d-3d1500437db8)

**Comment by SvenWerlen** [comment]
Hi, this error was also reported here : https://github.com/SvenWerlen/moulinette-tiles/issues/13
I just released a new version of Moulinette Tiles that should handle it.

**Comment by woodwardj** [comment]
Sorry, I just saw that after I posted and must have updated modules a few minutes before you fixed it.  I have re-indexed and subfolders working now.  Thanks

**Comment by SvenWerlen** [comment]
Great. 
No problem. Thank you for taking the time to report the issue!
