### ISSUE TITLE
Updates not working properly

### ISSUE THREAD

**Issue by LorduFreeman** [SvenWerlen/moulinette-core#76]
My Moulinette Core is up-to-date according to the Foundry browser, no newer version than 12.0.0 available. Same if I reinstall the module - gets me 12.0.0 and updating it says it's the most recent one. Same thing on a different instance I'm running local - it is not possible to upgrade Core.

I know I can fix that by manually installing the new version but I'm quite sure a lot of users cannot and do not even know about the lastest version difference.

Origin of the error seems to be your manifest entry at https://raw.githubusercontent.com/SvenWerlen/moulinette-core/main/module.json which still sits at 12.0.0 and points to the 12.0.0 version.

**Comment by SvenWerlen** [comment]
My mistake. Latest released version is `12.0.0` indeed. Newer version have not been released yet but will be available soon.
