### ISSUE TITLE
Add Unsplash image search to moulinette -  image search

### ISSUE THREAD

**Issue by CyberFoxar** [SvenWerlen/moulinette-core#9]
A suggestion rather than a proper issue but I figured it could be useful to add the Unspash image search API to the module.

Unsplash is a website providing free, beautiful stocks photos and images. They're available in a wide variety of resolutions and formats and their API is quite well documented, easy to use, and free (for reasonable volumes).

Their website: https://unsplash.com/
And here's the [API doc](https://unsplash.com/documentation), as well as the [developper portal](https://unsplash.com/developers) where they talk a bit about their pricing and such.

**Comment by SvenWerlen** [comment]
After unsuccessfully trying to implement this, I decided to improve the image search module to support Unsplash. In version `v-10.4.0` (moulinette-imagesearch), use your browser to search images on https://unsplash.com/, then copy the URL of the image. And use the "clipboard" action in Moulinette.

![image](https://user-images.githubusercontent.com/938060/215938207-35840a0a-3c98-49c9-b932-03fb8e8f4f20.png)

I hope this workaround is good enough for you
